name: Daily Blog Post Generator

on:
  # Schedule the workflow to run every day at 08:00 UTC
  schedule:
    - cron: '0 8 * * *'
  # Allows you to run this workflow manually from the Actions tab for testing
  workflow_dispatch:

jobs:
  generate-article:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu as the runner

    steps:
      # Step 1: Check out the repository's code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Specify Python version

      # Step 3: Install the required Python libraries
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the Python script to generate the article
      - name: Run Article Generation Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # Inject the secret as an environment variable
        run: python generate_article.py

      # Step 5: Commit the new files back to the repository
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Add new daily blog post"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
